### ISSUE TITLE
Improve reports

### ISSUE THREAD

**Issue by Nethermane** [Nethermane/react_HCI_325#11]
Add dollar signs to everything in reports.
Amount should be with a frequency

**Comment by rykrr** [comment]
- Re-visit the use of nested tables and consider having sub-report pages for each month as a replacement
- Report graph should show present/future spending alongside partial historical data
- Report graph should indicate monthly goals

**Comment by rykrr** [comment]
Commits aee1cdf and f37b93d address formatting issues, projected data, affordances, and frequencies.
